test: disable Python 3.13 CI xapian build. Fails with compile error.
...
libtool: compile:  g++ -DHAVE_CONFIG_H
-I. -I.. -I/opt/hostedtoolcache/Python/3.13.0-alpha.6/x64/include/python3.13
-fno-strict-aliasing -Wall -Wno-unused -Wno-uninitialized
-fvisibility=hidden -g -O2 -MT xapian_wrap.lo -MD -MP -MF
.deps/xapian_wrap.Tpo -c xapian_wrap.cc  -fPIC -DPIC -o
.libs/xapian_wrap.o
xapian_wrap.cc: In constructor
‘XapianSWIG_Python_Thread_Block::XapianSWIG_Python_Thread_Block()’:
xapian_wrap.cc:87:13: error: ‘PyEval_ThreadsInitialized’ was not
declared in this scope
   87 |         if (PyEval_ThreadsInitialized()) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
xapian_wrap.cc: In constructor
‘XapianSWIG_Python_Thread_Allow::XapianSWIG_Python_Thread_Allow()’:
xapian_wrap.cc:109:47: error: ‘PyEval_ThreadsInitialized’ was not
declared in this scope
  109 |     XapianSWIG_Python_Thread_Allow() :
  status(PyEval_ThreadsInitialized()) {
      |
      ^~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:782: xapian_wrap.lo] Error 1