bug: roundup-server logs connection aborted for http 1.1 clients
When curl conects using HTTP 1.1, I would get:

  ----------------------------------------
  Exception occurred during processing of request from ('127.0.0.1', 61356)
  Traceback (most recent call last):
    File "/usr/lib/python3.12/socketserver.py", line 630, in process_request
      self.finish_request(request, client_address)
    File "/usr/lib/python3.12/socketserver.py", line 362, in finish_request
      self.RequestHandlerClass(request, client_address, self)
    File "/usr/lib/python3.12/socketserver.py", line 766, in __init__
      self.handle()
    File "/usr/lib/python3.12/http/server.py", line 438, in handle
      self.handle_one_request()
    File "/usr/lib/python3.12/http/server.py", line 404, in handle_one_request
      self.raw_requestline = self.rfile.readline(65537)
			     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/socket.py", line 720, in readinto
      return self._sock.recv_into(b)
	     ^^^^^^^^^^^^^^^^^^^^^^^
  ConnectionAbortedError: [Errno 113] Software caused connection abort
  ----------------------------------------

from roundup_server after the client exited.

I do not get the error when using curl in HTTP 1.0 mode. I do not get
the error when using a browser.

I have added a wrapper around the handler to capture and toss this
error so it doesn't get reported.